### ISSUE TITLE
Screen Flicker

### ISSUE THREAD

**Issue by khalidchawtany** [yatli/fvim#140]
I am on Mac OS 10.15.3.

When I scroll through a file the screen flickers very annoyingly. 

[Screen Recording](https://youtu.be/GoILqovUN2o)

**Comment by yatli** [comment]
Thanks for reporting.
Any other macOS users to confirm?
I still don't have a mac at hand, sorry :)

**Comment by psliwka** [comment]
I can confirm this affects me as well (macOS 10.14.6, fvim v0.2-247-g7a2270c). For me, flickering happens not only during scrolling, but sometimes even when I move the cursor, f.ex. by holding HJKL keys (I know, I know :P), or virtually any other operation changing screen contents (switching between normal and insert mode, switching windows, etc.).

Unfortunately, I don't have skills to debug this, but I have a few observations which might help to proceed here:
* The issue remains reproducible when fvim is started with `-u NORC`, so it's not likely to be related to any plugin.
* When the window flickers, it does so by briefly becoming transparent – that is, it doesn't turn fully white. Instead, one can see the contents of other windows underneath for a brief moment.

@yatli: please let me know if there's anything else I can do to help. I've just tried fvim for the first time and I liked it a lot, but this issue is a dealbreaker for me :(

**Comment by khalidchawtany** [comment]
Maybe you cannot see it in the screen recording, the filicker happens as a rsult of window becoming transparent for short period of time.

**Comment by yatli** [comment]
@khalidchawtany @psliwka could you please try the latest version (v0.2-258)? I've updated the UI libraries which brings performance improvements and also fixes for OSX.

Thanks.

**Comment by psliwka** [comment]
Just tested; unfortunately nothing changed on my side.

**Comment by khalidchawtany** [comment]
@yatli the flicker seems to be gone however, I cannot resize the fvim window and toggle fullscreen fills a quarter of the screen. When I toggle off fullscreen the window is maximized and fills the entire screen.

**Comment by yatli** [comment]
It's most likely again about the immediate GPU rendering...
Will look into it.

**Comment by khalidchawtany** [comment]
Explicitly setting `FVimCustomTitleBar v:false` fixes the resize issue when not fullscreen.

**Comment by yatli** [comment]
Ah, also that.
I should set it to default to system titlebar on macOS.

**Comment by yatli** [comment]
@khalidchawtany fullscreen still only cover a quarter of the screen?

**Comment by yatli** [comment]
My macOS VM just refused to boot these days...

![image](https://user-images.githubusercontent.com/20684720/88416424-c9e23600-ce12-11ea-9278-0d846bb477c2.png)

**Comment by khalidchawtany** [comment]
I don't know why but fullscreen is OK now.

As for the resize the cursor changes near borders. However, cannot drag it.

**Comment by yatli** [comment]
The native macOS fullscreen button executes system logic (unlike the FVim one) so I guess that's the difference.

Resize problem persists even with system borders?

**Comment by khalidchawtany** [comment]
Using system borders everything works as expected.

**Comment by yatli** [comment]
FYI: https://github.com/yatli/fvim/issues/98

**Comment by khalidchawtany** [comment]
@yatli I don't see any flickers anymore. Feel free to close if it is fixed on others ends too.

**Comment by yatli** [comment]
@khalidchawtany thanks for getting back. I verified it on a vm and no flicker observed.
let's close it for now.
